default_install_hook_types: [pre-commit, post-checkout, pre-push]
repos:
  -   repo: local
      hooks:
        -   id: run lint
            name: run lint
            entry: ./pre-commit-scripts/pre-commit.sh
            pass_filenames: false
            language: system
            stages:
              - commit
        -   id: clean and build
            name: clean and build
            entry: ./pre-commit-scripts/post-checkout.sh
            pass_filenames: false
            language: system
            always_run: true
            stages:
              - post-checkout
        -   id: run tests
            name: run tests
            entry: ./pre-commit-scripts/pre-push.sh
            pass_filenames: false
            language: system
            stages:
              - push
